
#' Create a .csv file for Cytoscape
#' 
#' In Cytopscape, use File -> Import -> Network -> File. Select the .csv file
#' generated by this function. There will be a popup window. The source, 
#' interaction, and target columns should automatically be identified. Click OK.
#' @param graph A 'network_plot' object. See ?plot_network().
#' @param output_name A name for the .csv file.
#' @param dir (optional) Output directory.
#' @export
create_cytoscape_file <- function(graph, output_name, dir = "output/") {
  
  edges <- do.call(rbind, 
                   lapply(lapply(attr(igraph::E(graph$graph), "vnames"), 
                                 strsplit, split = "\\|"), 
                          function(x) as.numeric(unlist(x))))
  weights <- graph$edge_weights
  
  #Determine number of rows needed for .csv file.
  n_adj <- nrow(edges)
  
  #Initialize table.
  edge_table <- data.frame(source = edges[, 1],
                           interaction = rep("gg", n_adj),
                           target = edges[, 2], 
                           scores = weights)
  
  write.table(edge_table, paste(dir, output_name, ".csv", sep = ""),
              sep = ",", row.names = FALSE, col.names = TRUE, quote = FALSE)
}