
#' Create a .csv file for Cytoscape
#' 
#' In Cytopscape, use File -> Import -> Network -> File. Select the .csv file
#' generated by this function. There will be a popup window. The source, 
#' interaction, and target columns should automatically be identified. Click OK.
#' @param graph the p by p adjacency matrix (0's and 1's) of the network.
#' @param scores (optional) the p by p matrix of scores (weights) of each association.
#' @param gene_names (optional) a vector of names for the p genes in the network.
#' @param output_name a name for the .csv file.
#' @param dir (optional) output directory.
create_cytoscape_file <- function(graph, output_name, dir = "output/") {
  
  edges <- do.call(rbind, 
                   lapply(lapply(attr(igraph::E(graph$graph), "vnames"), 
                                 strsplit, split = "\\|"), 
                          function(x) as.numeric(unlist(x))))
  weights <- graph$edge_weights
  
  #Determine number of rows needed for .csv file.
  n_adj <- nrow(edges)
  
  #Initialize table.
  edge_table <- data.frame(source = edges[, 1],
                           interaction = rep("gg", n_adj),
                           target = edges[, 2], 
                           scores = weights)
  
  write.table(edge_table, paste(dir, output_name, ".csv", sep = ""),
              sep = ",", row.names = FALSE, col.names = TRUE, quote = FALSE)
}